apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
  namespace: vitorflix
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "qbittorrent.test.vitormuzzi.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: qbittorrent
          port: 8080