apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.80.3
    chart: tailscale-operator
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
