apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-pod-cidrs
  namespace: tailscale
spec:
  hostname: ts-pod-cidrs
  subnetRouter:
    advertiseRoutes:
      - "10.96.0.0/12" # service cidr
      - "10.244.0.0/16" # pod cidr
      - "192.168.1.192/26" # cilium lb-ipam-ips (plus a few extra IPs)