---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCVJ2OS3ZNoLc+2aBsv3MxBFBilhXgt25gKTkzKO7PDBrY6oba9UV1/p6av08plgMY/v1MsG4W6o/esLQxL8TJDyNCVfmEbeN2ylQ/dfssirNDLg2/032TrRGznix7dcHCQBh/9ajSs9hEM02qQVVYUQFoA5lOmDdnWIFar3Gcs4Pij0gqIZ1O+HZfP48dhcqF3sVwHaFNwjXOWs+p9AlhF1tcd+VgRqOgQmIYt9ahjNqst1njX+rwQEcTxJ/HnAXyOz7mKsvi9XmokLhbs5My1irqsQAPTAMIeWoTY3S+rKedBrJs7qG529I8NKVJrv1PeqlpLwg+AgKEduHuu2OVT5x8YFtrVanwfLq9UyMUN1Ts/n/0EBq3ppY4zB1oWAojb9CffN/MmyiN7kGb/Hk5zTgqYLM52rz4K+3uEkOWKeNB0fzDnxQA1PBDUdTfp4LrYGy8UP1Z7FgzkzJpKBh+UygQCfrfrvcNgPpGxnpeZdz5egUSBUQy7mBZsfeE8yr65LjJgd5tym8y6g9SVwg2TEstgi3I0vOXkQz0d+cLe/2e/+Qc0rwH+FMSymEQERzXtI44vIwhBnulTw/R4fc9UVWSzBDVDH6HZPL9lXkRZVpDYg6y3LYlpfb7xfvxnyrEOOuaBrSwo6OMSTqYFtRbfVPEwY8ziBwQgGAPTYlxIer7ylJi6MZgKuhFFH2pL3fKm7cQ4V0FE0z5zqlRlytdfAg==
    client_secret: AgCv+k16LWO2k4qYEBuXtI/elbINhiLEY8CY2dFmYgSSiLlFSs6mPeMRpbZSotnXIQzOaUbIskYzZ0xqOAblTmbGjjqsP0a4ACMMZM8f5JriiqD6Wb/RpuOpkJKA9adVqtUZB+hKvEWTyYm0L/b+Q8/HNO4FoqDn5zQkWnn2BH5z43egtHjUqKD+SRss4s0/mjp7BpgccorjMAsWPC2REnZXe9Yt+ps5SQCIpPWJ5GgKCbpsOWJ3rbOoXS4JSwDNk2+Q9p1b/z30tN82+ZT1beQVxjRdb7NoWJ0hsTa3wB8ctQHFp6EVBY4+nXEM5W9GaapFr6nEf1d5sNv5g8AtgarRcw52SH1EszFAmrYExeQcm5my2IsL/FHknU18ng6ElGEW/C32XWPQyXsWNBpp1RrvzKsm68to7BDgHIw4h/QcpzXUGgk9zwm7Ia1WLXum75/AVML0qwP6sGUjCNpGcgiO63lXRpI68r9MPJZENtjazV7yWJmXC/pd5SoEO7WfLUCOrwwByXYq1DmiQQ0eGtnNMULXCpB8efNQJTM4nokQ2KFKVL7PcFERjtTuQzKx7X8o1BgyX1NTa3JFZ6+ImjDNA3a6QkDU3A8GiGt5RBL4wtocFpiQnativcC9hu3U5iCqsbWvOoVj21NsMedDeifIjV/Rz9pXLEKAeR1dePwXCHI698UtlKbeQ90hkEKM4fc6ODyfYBjfEKWtl7ea6LdfPtL3OuAA6EWoKcTU1aRB/eMGfFiUdRcCYhHzuVfRJSBsjwzhRWwh49Lx68GlxuYW
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale