---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA4nfutSU8MKrkZhouHPM2DBZn3fcp/J5eRra/D0Djh3UXg/UbHRHhudBi5CrJy84/3tLAXRrp/M57bKsUz0LqC0I8L8iGb0sVCXy+YiucVtijE7yTvaiydukSEpuPjvx01dYIgfCk3jfkKd+6PMgg4fBAWlajK6ZhSEllrY7cFoEAfgrrB95FFMtjSBj+0RVbdTYEkIDDCQ+WwfymelYQls5BQrT3xoT8NdIU8Bm3Xfp3paJHkngZQkud30mYl0yb5zASpkThvDMPGpoaTo7/HXPcrPUykX478WmTysYxuRuq1M7wvCEx0UCHZmIL5xec8DQT73gzYuAShcECemnvxwmE09ebp0eb3OfI1oYyheM4VFrocHaJwjMSbXYWQP7TtEVytcBeAdoS5Ho78h8MrdvpFD6+2ZfkURG8PqwF1by/t38cCoFlMmK59Css7VbOrICJRgCPECS9J7I/xZ0yirAWBcbxyNtUtSDyPr3BjB7pcrEvomMQ6TS0yqEAZrjslu+msxrc23qQlRPXadw0n9VP88tZhM95KoIhzHF2E+5zj3HXPY6nAyh7v8NDeRXGcOgT8+TUJjDt4dhYdKNYnu2PMOKOOBwh7mwJk+HG/EirbfDX1V0dRqJBQK4UyGAk4JHQ34JDFWcDPupSCKKv7x2f+rAbXOiZ25ySTV11Ib0ORwu+uZ3PCTXNgeomzP/vnxU50W1Ndi4hlkLo4vDhZPQ==
    client_secret: AgBQjsUQ+ideJ9NM9pSV46zuyXKeuAkVMNQ1x9WnDESAfI72Ibi0P0dNcFAEJbAWH2RaVQwKtazXR+pkat9F9gqruPPCXllipCmSnYKKxNb25A21F5/SSNGQRyzFLuP40rdBTRufiFkMCQr05T8eQGaDhR86YwydQmMDEO1eGMtvwbLwnL/dKysF3MGBOUUk0aTEbwhJjR9pBxuHJKkPnL+eCn/5CAYP0WpkuJFIdiNhZD95kW/NS3rGN8wPlljFg3scCfq8BvuIDDbpt/ZDkovjH5yqsaBVu5CQaF7NinTabCgJ8bw/wfmNKLgrToKwBD7KGlSWTp+Ttl8msj/Dymh2nEtNkbTWr+ngP6pzXaED0wnJ/K75RwZ+8+xVPwq4/yeR/wbHwmV9KTSBGh6/HdDQnqVAUFIni6RBb/h6PvpsDj6g8dp1aCUgi+kU7+Ikf88MowX/gkXcVYU+QX+xxixAz4Hdmwd+0p2h1KU+XaPGcOG2oPAzw8YuZpYi6ccgso1vpGleaBBbfpLHGXOLfYAR7uUfo037T/oQwA/GZJAEBYZroI76GpKr/iyoYK1S44f9rhMaZ13TW/O2/TWxJqKQ+HNgVSBKdAQ4gvab4zSLYjsAXJAyCoNjeldnf02DnDnLupbRdYBArMNo4FII5WBmsKWLPAFE+LSHCU+jeW6/tg5XCwoC32V5KohsmaHwsnwFlZt/gh4BMouOHcbk07vHe1WrOPyZF8v898H0XtJ8MCieKBuG/vFhWzVxkk+cYk+rFYGJJgCNF6Ugua880eso
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
