---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCza3u2sRuAzVMEqBB/0hziltZZNhWDdqXIerzZsTJhvhEZhttb+De6ARHZm+fpdjSUuGa/KqCZFujXtGzs/jdiDF5rrvNjU2Z8zEGOBdYGgOXqhAwz0Q9wDKz3fYvszoUTFe/wKq/qbzoknG64rSsk9NKr2+Sn2TiSJK/pGfJaXGjeb808YyHz+5BoUHLA/gyHfvici7KdxbrcQKQ/mzq2q2eFJOoauAYXf7rVxNpxzIA7+JKSzwKsn4YH8y0WNttQBYDp+zpvH4zldTfPJj1MJA6fHL3qzm5E5g5Dr2bRzAbCpxTCe+x/vyZ84tgITK66AKDAYinKkjhm6GgBhfXktlchrczC7Hs0nayKkYQ1NwlXeGPnP/EafEW/iSAKX5BhkimfmNPYpxCEH7ze83AZ+dyr66JlAdpZdV+bmCcLdm9vI9UOYwVFkeuPeCJKsmrLszP7KKaUk8Z7Nh850l8fGGHKTEe0x2tvbxpElrkP3VjqPxwYsKWu/kwh4g8CuV+FZHZ1Gy3hgguUpVlJ3aXtflYZc6uSaPtylT+1b04vJQpz2A5rQJiQEUSmmN6CuIDww1Xj6SoA1/zvfkKrfLMqxv7V1Rx/1jjnHmX6VadM/kH1TPE/9ASERnI8ztUkl65RSXEWBx/AENimm1XfInAnL7F0xQhudAOijS6ggBcdNu2VzorXMUeYRc3Lg35KblMfceGj0tOAesndh6pmyQNEWA==
    client_secret: AgCySXUVUdhvnSiLH6npo5/0O0ziF3BXmOClD5VBSB8xf0chqwvhp31MWF3efg/jh/Z6C07yFgzHtzps1YJvBWJnaSDbp+chHlqbZdIBjTZ4qh5MwwiejmKNwGp05Qm/AlYf5cVNyEJ5nAYKD3PyD8ZXcICO4fiG/dxZZlDFd0iyHYn6KAhvfcDDHGrHN8CdQjA/jC1LpG4oJXPHixFffBRY+8Um49HN4Yv/jMrFiZFX/OgNTfhL/v/8b5/vxSa/7FHaz6SxruH0JC7ApWdGY/CCyx3FPVJHRZmW2KNEDh00oH+RaBloRLE4jqGgtmfR9ML74r9sveCFWr4fIwcxmnalVmacB4zqPaUyVM8VTLEx3l7gCbrVUgLyCi9QkotQ7U9U+QvGKy3yUE8yLdKq6OHheVQuovPGfJm4A/MBKCduO35W3T7af/Xa0rt6+sJELhrfSElrct3+etDHlL6azJfum5c9+2pE/4l8GecCQ4e0m/oDF1Io09tD5KzcthL3qeug5v5D0NFj9CEMVustEHQaUnJ5GFReCGPnUQWtvJk5BcCSHhMfxO6JW7fTGIi/zbQf0uL0cktHQx+wsKblmEzv3bX7FxCifuKIKELFPeUHTGgWjfv0wBeuFmVtug1xPM9zbZ1SfGZKpL4ZxKKMJJQESSK5n8va+WSA3L9c1RO4j/tU0NZezQf1m10EyKg8GrEcF+fVdSZMdORdEjiQE9FzVterX7NdixBiw/qmJ2zWk2Exs2rZIrDNBeukWQm8VUP1e5EAEEq3F/Pa/MD9PJd1
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
