{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "operator-oauth",
    "namespace": "tailscale",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "operator-oauth",
        "namespace": "tailscale",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "client_id": "AgC/WJ4JoZcQtOG4fZ66YLWuRiy3ePAx72vPrYMKCJbU1UDWod3xN8ZvKm5N2sJ3bgRlAQMpzsCG//yuzAF28tePpDGPIpSyljD+LN+qZFnZMWKd6kzYSFOr8ngd9PcB1z17OIynqHvo1kl1eA7r9TEnEacXACibeTJctlcYjRLugtdmmpt9B/O3dGisGoyi9KxELXCOY5+10gSO0dCjKIuh+wOaQ06PluHHRZzLJOxYv+7qm/sxmJUX+nwq3KxX4VaIoQVwV1yr486J/4Bt5msUNyiTS1jTjTwZpuSN8lSfNy8QppYH8oMwohSOBN0n2tTrTfugLkcw0drUk3u8rFcaNkLevMG8EX0GnPGqvdj+yVHTqtEFoGyOjTXKugJvb3TIrrLfBgIafxNV9eQy43nIdt4Gy5WCceQUIzv/ExgiWz71Ux3I7m8RQtgMW0Nxv1yOcxOBg5WGQ6rr2YGvAZsvElLa1l06IgoWHaHaTNKJhvD0m/vzLwYOZgWjBem1GqFOYN1uqWBl7pvWDE1wo06lIzm5bUg869/jfxtmM6D9acr6QN0s/9QblYDshHvlMIP16XF7YwWybkNXK+goiw29fYqBRaCvpvVxIJLdl3SDC2uYxmrZ42/m3Tbr5AqmON9hTCrMllX4vBVEa6F/8aQIckyJmJ3lKuRqV2I0xFP7W9qFCROBuAyrGMqwEA1//WRsTjbXggq2rvhKKbHCdHpY9w==",
      "client_secret": "AgBt5u4M6y60BuWiGCurwgqJRY3iNuxhH5Jfwy+c/jzx+3H9gMBgPasDWKw7HxPr0BFwCOIOb5yV1rSzOiT3CDEIqcS/Bj8uzGkB3a9EH8pLgbhiIFnkj4Sb85EgM+tAFq/Hvtu/bhvxhxmg2obP/SExCOdqBe9SD7OjCeBWXcIJIrj/nJFJqTVwKdz0KhKLgT9x0OuOS/c1nst0hBPOEgBnQHPWUD9xrxYi8n6BsAotY/u4mxlEsIBQL2YQIgg8Z6fCvdSWqJhhFwSh9hrnqSfCIs8R/brCs1RDkZU6rYy1A8f54amvKPxC8uOSsdUqwTEhv/Ka5RJ0XVCU/LW8o9oP5ZrKhnSUvQGmbqQWUWxYRgEmRYaiv5SCS1k58PuAXIp+EYJGCAdJ6P01ClmGPyDkq2uv0dXLzB7mmPc4m/7twhOJRj5WUyS5ppzox/tRqELOK8CgkimYXCwTWCMVIRDo45+N+YyxjvlJO61NWA/8Se3yXJRHox7h2F8QQarukEtCEOtyhqRPFnHcBDTiuLm6mVV0rpM+v4qwEhHqI4BPzchjxgEW8+rx8gP3EA7IXtoqjTWne9Hf0fCZ13YKlpa7u+76Zq+VC3bHn+Eka3yBDApjg0pM9GmFIFawkO3LHliNivqfc4CGfofOyDtNp+jMqRdzzSWh8Dqnwu4HAB2GeVbErkwTnIqz7j0ewcY3QPCQp8JCN7sESVxFPcyB1koVIqagx/TcLusKjtzmf7mrl2YKZYmxLbPwo2STk1ea7g2NrzUyDF2G89tQmYXzMYw="
    }
  }
}