---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBsAnvR3K0JctocWW9Lp+krRnqXZrCGhE7o4Oo8TN0EbDTLcacgynZa4Q7p0UWpwQ4FXJHNoYT+ASIaKozPCvWAVf9PeoZa9EBxohQrL1ssLGVkQVSVUdexiGDHrFiE6ECuJhhUqZtbrom6nY57bL8mVmXgw++IjGGTXgr0lTnhniNpFiuN6uI4jEYuH1J+VzKnDo/ZLYtjzMHHYr383NV+T9GPw5OgbZ6S9Uhbyaleowl3CxTzs/y99D81U3qB6KxhAVC6quAkurREX4jF1DO9ARhh7aVc1DHT+IZP63qxYiwR3t2l+JG0DXEsDnbg6heJpf8BOEivhqviPeZwBYH05iVnbv9Gh0jxBAvG3aTvLCxEoEzWBoT7WX4352smrXNqpQqYRr9kJHKwMJFkedjbD6MhK6hPnTdcjDJkPHg5aXwDd+HIm94geuVuuYmmv2L6ia+S5ePdPunSKqta7rcwfagAPBuCVGR0sWVQRhMkvKpLIWcUyQfiohSCNsqdAEnPagxF/a3xm4Lykzh7x+ICuaGWXXYemY+FEQ1Ypqxvos9EtmI482Sb8MA5cD63KyY07WkEWLbPU165dG3ccMxrH3nvb6sM4V8mpiyFlxA+imXfZ2z8GpTBDElR3AI/H6hS6KHbH0u6TKhxe+dkVyY6oSDt/l2IXXum5iN6A+qCif1ZOCNQHja4wWzj7wovn/pTLemZ859BfIv7mCZMTZ4qcQ==
    client_secret: AgADJW6VAu7q/hmVmbn40/s4XR7C5bn/4i/3ymoMTpwkzHEFosf5Y/E2Il+fI55e2HIMkH5csf7ioUViRNzC2ZS6fRJxsnzBfAkC/xbX+xiM0Booi/IqjAcsfEmehvqcQxSJVJEBDzo4YTAn6jQw2v70UmPqKF9ZfJr0MDOQ4LJcgogaRz0ghr1eP34DIePHbl6JKWyxlCcaftyOb0dG6vzIAFA7LjkcqTXyXij9tYIIMyEM3fdRluMVx922LHvsVQ177qVvSnksr0s45YIVHWp9IZ0eLvI6LAADrqSM4KGXMViYwWWHazCY6cuLHs/Egz4AuS5FHDUv6kRpJYTZ8GSqquPyviMPKBbByCvL3eyjEY89ZElsTSrdV16F7wjqaTvpNzBLcN+3QKAjt/cIod4GYj5sUI+k81KqvT0pFUWgm8bq9cdVhUWGouffUvhOY6HTlMCN0A9dkJggQD4ONEkoJMdqAg0ZHne5Fl0OrTH55T+XQZ/WrqGU03nR9n0yKDcmua07vynFdbut3kOo3+0WcXd6ijW9LWASORi/WsoND8bcrFOwGYZtYx0ZF1hOpQwgSitbR6pkAcZYLsKcEJezWHzE3n201w54mVocR9sWyO0AgIP7vVOR9B8R12NINdaVSjeRPqJkWdkwtzP+a2UzALHwY3RdbGtpBkmQn5uKdD6XjUMLGWMBaWwbXPQtxkZ6bVfhNRsrrSlPpbCixPMVGoUETCh3qU2y/yMIdElohrVs4kttWli/A5rmm2g/TmgBOsoScWtR2A2nIrUZV6y9
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
