apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-vitorflix
  namespace: traefik
spec:
  secretName: wildcard-vitorflix-tls
  dnsNames:
    - "vitorflix.club"
    - "*.vitorflix.club"
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer