apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 34.4.1
      chart: traefik
      helm:
        valueFiles:
        - $values/argocd/traefik/values.yaml
    - repoUrl: https://github.com/RelicCornhusk/homelab.git 
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true