apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-jellyfin
  namespace: vitorflix
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: proxmox-csi