apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-qbittorrent
  namespace: vitorflix
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi