apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-lidarr
  namespace: vitorflix
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-csi
      