apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-radarr
  namespace: vitorflix
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: proxmox-csi
      