apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: vitorflix
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: proxmox-csi