apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: vitorflix
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 120Gi
  storageClassName: proxmox-csi