apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bazarr
  name: bazarr
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bazarr
    spec:
      containers:
      - image: ghcr.io/linuxserver/bazarr:1.5.2
        name: bazarr
        resources: {}
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /data/media/movies &&
          R $PUID:$PGID /data &&
          exec /init
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config-bazarr
        ports:
        - containerPort: 7878
      volumes:
      - persistentVolumeClaim:
          claimName: data
        name: data
      - persistentVolumeClaim:
          claimName: config-bazarr
        name: config-bazarr
status: {}
