apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jellyfin
  name: jellyfin
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jellyfin
    spec:
      containers:
      - image: lscr.io/linuxserver/jellyfin:latest
        name: jellyfin
        resources:
            limits:
              gpu.intel.com/i915: 1000m
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config-jellyfin
        - env:
          - name: PUID
            value: "1"
          - name: PGID
            value: "1"
      volumes:
      - persistentVolumeClaim:
          claimName: data
        name: data
      - persistentVolumeClaim:
          claimName: config-jellyfin
        name: config-jellyfin
status: {}
