apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jellyfin
  name: jellyfin
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jellyfin
    spec:
      containers:
      - image: lscr.io/linuxserver/jellyfin:10.11.6
        imagePullPolicy: Always
        name: jellyfin
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi
            gpu.intel.com/i915: 1000m
        env:
        - name: PUID
          value: "1"
        - name: PGID
          value: "1"
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config-jellyfin
        ports:
        - containerPort: 8096
      volumes:
      - persistentVolumeClaim:
          claimName: data
        name: data
      - persistentVolumeClaim:
          claimName: config-jellyfin
        name: config-jellyfin
status: {}
