apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - image: lscr.io/linuxserver/jellyfin:10.11.6
        imagePullPolicy: Always
        name: jellyfin
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 4000m
            memory: 4Gi # Lowered to prevent OOM conflicts with the qBittorrent cache
            gpu.intel.com/i915: 1000m
        env:
        - name: PUID
          value: "1"
        - name: PGID
          value: "1"
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config-jellyfin
        - mountPath: /transcode
          name: transcode-cache
        ports:
        - containerPort: 8096
      volumes:
      - persistentVolumeClaim:
          claimName: data
        name: data
      - persistentVolumeClaim:
          claimName: config-jellyfin
        name: config-jellyfin
      - name: transcode-cache
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi # Caps the RAM disk at 2GB