apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lidarr
  name: lidarr
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - image: ghcr.io/linuxserver/lidarr:3.1.3-develop
        name: lidarr
        resources: {}
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /data/media/music &&
          chown -R "${PUID:-1000}:${PGID:-1000}" /data/media/music &&
          exec /init
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config-lidarr
        ports:
        - containerPort: 8989
      volumes:
      - persistentVolumeClaim:
          claimName: data
        name: data
      - persistentVolumeClaim:
          claimName: config-lidarr
        name: config-lidarr
status: {}
