apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prowlarr
  name: prowlarr
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prowlarr
    spec:
      containers:
      - image: lscr.io/linuxserver/prowlarr:latest
        name: prowlarr
        resources: {}
        ports:
        - containerPort: 9696
        volumeMounts:
        - mountPath: /config
          name: config-prowlarr
      volumes:
      - persistentVolumeClaim:
          claimName: config-prowlarr
        name: config-prowlarr
status: {}
