apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: radarr
  name: radarr
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: radarr
    spec:
      containers:
      - image: lscr.io/linuxserver/radarr:latest
        name: radarr
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config-radarr
        ports:
        - containerPort: 7878
      volumes:
      - persistentVolumeClaim:
          claimName: data
        name: data
      - persistentVolumeClaim:
          claimName: config-radarr
        name: config-radarr
status: {}
