apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recyclarr
  name: recyclarr
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recyclarr
  template:
    metadata:
      labels:
        app: recyclarr
    spec:
      containers:
      - image: ghcr.io/recyclarr/recyclarr:7.4.1
        name: recyclarr
        volumeMounts:
        - mountPath: /config
          name: config-recyclarr
        - mountPath: /config/configs/sonarr.yaml
          name: recyclarr-configs
          subPath: sonarr.yaml
        - mountPath: /config/configs/radarr.yaml
          name: recyclarr-configs
          subPath: radarr.yaml
        env:
        - name: SONARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: vitorflix-api-keys
              key: SONARR_API_KEY
        - name: RADARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: vitorflix-api-keys
              key: RADARR_API_KEY
      volumes:
      - configMap:
          name: recyclarr-configs
        name: recyclarr-configs
      - persistentVolumeClaim:
          claimName: config-recyclarr
        name: config-recyclarr
