apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seerr
  name: seerr
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: ghcr.io/seerr-team/seerr:v3
        resources:
          requests: { memory: 256Mi, cpu: 100m }
          limits:   { memory: 384Mi, cpu: 500m }
        name: seerr
        env:
        - name: LOG_LEVEL
          value: debug
        - name: TZ
          value: America/Toronto
        volumeMounts:
        - mountPath: /app/config
          name: config-seerr
        ports:
        - containerPort: 5055
      volumes:
      - persistentVolumeClaim:
          claimName: config-seerr
        name: config-seerr
 
