apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: vitorflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - image: ghcr.io/linuxserver/sonarr:4.0.14
        name: sonarr
        resources: {}
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /data/media/tv &&
          chown -R $PUID:$PGID /data &&
          exec /init
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config-sonarr
        ports:
        - containerPort: 8989
      volumes:
      - persistentVolumeClaim:
          claimName: data
        name: data
      - persistentVolumeClaim:
          claimName: config-sonarr
        name: config-sonarr
status: {}
