# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: matter-server
  name: matter-server
spec:
  restartPolicy: Always
  containers:
  - args:
    - --storage-path
    - /data
    - --paa-root-cert-dir
    - /data/credentials
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    name: matter-server
    volumeMounts:
    # - mountPath: /run/dbus
    #   name: run-dbus-host-0
      # readOnly: true
    - mountPath: /data
      name: config-matter-server
  volumes:
  # - hostPath:
  #     path: /run/dbus
  #     type: Directory
  #   name: run-dbus-host-0
  - persistentVolumeClaim:
      claimName: config-matter-server
    name: config-matter-server
