apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-csi
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: local-btrfs
  cache: none
  ssd: "true"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate