---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgAazrZPe9N5KBLPLHOCFYW1rOvrjV79T/DsvVL3R/HCRXAnj1JWzxSLfuqv+bWNJ/kv9gAwQoL8XZVbUPrzR3i1zb33CBeLWLvEOU0ZzRX+Ddy9i7369ntPsqY15IkhxfKTYFWM2pT4dRcPsqaFW/XDIhTtHDxQj06CLUWwaRP3saJ4O0oDSwrtqgZDNXUe39RdZVI97rAupxnVEHXJXno5myYBJbuUOGlI2Ud9fxB3jc9jxgSVm748nzZOa0o9pjakEEJDA5ovCYSBHlM74MVPRz93rTidHdr3ZiC8KXxHXzMZZlAQHtj4oDBE+YOoI3J6QncqC44/v55o3lutXD6e25ynx50I21AoXX1Uob0+Loi/MkLFt1UXK4fOYCnacjpKMwSPE32gBaeNvB9/8PREoZS/ggc3kZyEmYamKgH3THeY08I8BA7JopqEJ1TmYw5yshSll87AkUbIFLCp9fZr1T46sJPIagtz0h6XHxB9Ow+QKCs4KrfCrMZA4Dt6pzWjlxxpyjDejyd4VkNFXDaaIYLz+VF0JeFseqCcCLsdZAHQjYQvOYMaUqwQ8DBZ/WmletmgO+aPjIzM4a3CuLKf/mxjPhU6CpILRLiSlk/Lks40rcXtqh3zvo9R5JmqSI7hart0IZvgEkGzyc8h8tRLp9GJ5EfM66lKlPMur2KHEvmEBEWrUxuD/evGLsuM54aOgBVjpqIAXmjdwRZaFDlJfwa/uGdTIWv/sDNo0ExwMgYiwXgaYIiP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
