---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgAGCo53ewllWu6/RdzBisMMCje+0qIiBFKJC7H4NGSID5ddTGmNB+Xc2Vj2PFccnEpFQHwCIvAn4RaasR3x7XJvx2Q/Bel7/kKw8bGcbrin1Ue1eGvMk0RRd/LMfUIJIeFg1KUFDK78gCueWG18FI9tG0eMjUSICqHs1PBBb+jRHI3g9wfFmyIsCuRvLD3rq7Muqz3CIHKr4Wh7B90pkM3zXG4fyhnb2lfeuCnqrtifumhk5uG4tl+IZ1IhmgWhR4wfn3fzCt0awqSs3Pg1mjdXQuvzg4hv0PzY4/0V7WtNcOC33LFF4nmpJlE6MZ5wV7+/Kynwvq9x3i3Flasjxy5omraTGKxflKxYEnlCQqY34dqe5NtwahW1R1SUb6MtDSLzI/EDfWPHgCsI2c7bWLwYyV4apzLH0fpuAfD96UPxhb8TLWkXSwddfhoG5XQgU7jg1n6k8AR63CGxLYhAdrIX7UR/m+oLsZ8tPqbkTy3mlpHCo0GsR38AoSEhh8jBnIbdyOAJ4w5GbN+oupF0rLCf+LjTj+VfGvKAoy54fy1ks/zlVBZKNWoIFO+Q9qpcUlGlEuV4SO5FhyFMhafj3U0qNB2OA9kyCpJV4ULPnTTVo99YbzdHQikl+3AnX8ScB0q8yKQ5Ftf0QVR2/S6SqQC+OLtgkXPr+W0Ridt4LIgbVlwzOPjdGBopNI6VUek1NFmnVtR15OdOBmFHuhIPgp2c+h40WL+ZNIfavZcVFxoO/WhL/f5Z+DWg
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
