---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgBaAu/5ej5Gj6LYcO8FMGRjoyGd7Fuh6CRNB92CqVlsOX3lwf7TmIfDIKP2SdyszLV89eTPT5cLlZbEJVszAjGt2bIKYPdjK23Y7ADaTeam4MHdKLUZSlDzmsdPAVhkYHUGqto75RzS/8zXDi1Of1B7l681Myqg+s/Kfk8/vWg58DoA2nJe/j3jZ8XxyqMJ22dSs+Gz+JrdohL4c5idONsE6GUElkjFMLhU5kMjIjSA8jAOm8T3L9CqK1u+HxR86d06a0f103OliV4XTlxhGjboAQlihz20rF8DSPO5qRRiCc5EFucw3F7PxvUE8KuI2wfZjJO3CBNi7I6xnfK2NySBpufoZ1Rmypf6VNoX5B8OB0y8U8aJdG2LPaQ9JQkERepIycVavfYJckMwPMdhZULIqgYnzxnuoAOWIe1J53VH0R3IR/QVgUhWe9NEAFQ5znROR1AgXu+4F24ZSgZ609CpExi98I5btay+QLfNfGvmEifG4H8OzV4Mh2EPJ7TmdbH7UPE4yZSeZy2gIb8CpZx+rWp8shGxbzf/+Hwe4Zm2jofKgN3qcKhipdt9pGf+tJ5uX3hRn78rx1TT+EDOhOaRZRTcs9mfr7ZkakfQXifUvcWYX06fvQoxzp1hJ8vwVz8FZKdNLd4Lk034TvsTPcGNvJV4KnrbaEYrd4IzPErvu3JY9kUytQfvhDrbrpcKTJCZ6mM++cVzuLoDFM6gXsCC6mAzUHdK/AxiOQ3x+CYmFXTF+95xbxAf
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
