---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aurral-secret-env
  namespace: vitorflix
spec:
  encryptedData:
    SOULSEEK_PASSWORD: AgA3lUiPKpNhSYXOwYWkxmRHSSZBdGvYZOP2sTQxiT2zD5pm+j5PG62FYIuzBgPk27FcyeiUVtlYcc+0//HH3xSDpJ2n2key+nkAKb6RsGYJx8ykjntDZsmAyLWSKhoKXqDG5gW5wY0yCtv5QrULVdVk74nbjCT/mdzaJ6oQ8RyyIzVP5YXxfQLjhC20aJQsUkiX/Chog9ysg7TFpHG9mSo6Uv6XQSJQKTQbJTC+GWQYFe4nuzPCeJ4uY28VDI1L+oqrvY+51auMTFndlDZiFg19YaKWwIY/1NvD2bAOPWdc7WZlBf5FUbOLupdfIBBWm2OIeh5NwawBTihqM6uVpL+4BiHswz8UKI0gGABmQm7SBOGmZM+4ubKWKlZv9o949VbUWJkxxpeG/nQoskYcIkGpTNKbzz4IJWwtscS8Mf02u+k3AyPu+oaDwXNjv4nv7RQ3lLsxhjYbArApQrJrK0ZGzOvdTtVijSY7VpcQAkDMnHzryh3422rQFZaIYbYveLUwBkwJaONLe6cOYJTKEWCPP8QL81KwCELDdmn1mHnFwA08EtAupHAuioF/A77nYPywGFns7CrtYj0d4joghWNU7LkV8d+Kq0QY6jjXaNf9k371IIyoHIqjRkD9508FWjp2W2V+piw8Aw6PuD9mWXBIrHcj1aIrzmK/LBRq/ueJqZjxxtgu0Scayd8urMI0KuJAbdwssU7KpGkDEhITUmQ5YP8f3l2ygnQhIOil3tTBCJr4B2DdsDdj
    SOULSEEK_USERNAME: AgCfmqZpqAml7bR+FJpEf/sJGXMke3TzMJW1YTquUTgkk9REZAVU4ftaNIHy3pOZBEqKb59C1ljyHiYPTMV3XKjWixg3ng7BKNpkyh2ShXQVFMXVzIVCr2L5w+NmCSiIVNKglfjKiWEbwC6KCxMo5blCBOc9aViTtRSCXID3jZgaIqlG/OlVNfFvfr0YFbUchzN23iqx5FQG/LMTJfgj2yrT1T31nyq8D8JIWXlaHJ0seqr/OR+ajoN2whlDNDJAacf4sS2gJNxOE2ctDwjdYBI3HhKuxHnHE8DUNDNBJyeRQOI6PXm9WhHXDsYj1VlheOqQdj1SLwqcV2dyOEAskBvRqFVCyg/fuKlavv0oDDb19GKR0rOMv2a738rCApX663ZbTF2M+Hxe8HJKg/Tnar5AbD8EzitC0on60d//zT74iBzVS7vNihepBTXDxUL1gQAkI9tmdPoDDxLIes40jPJzLaXWqG4cG0NGz35NQrtxvrJXYqlyIzSnV7XF0iMXuyh8RuOHFosFZc2z5B/VmfVoV+1mne8lAkp2JhE2ZG9Plt2cKnHBxxYhrCtkCfZn/hoVXnwQBJPliRCG0M/bhzRyXcZwr13A6FLMuVa9xiShGa/QoV8uzXmjZUsT4eqhSWAB+qxun4JzySgLi+ca/gK29x6XVWeddUyO4faJwdKb/2sxnErPJQuasmIiUETdCAKmR5E2xx8FmKEDyw==
  template:
    metadata:
      creationTimestamp: null
      name: aurral-secret-env
      namespace: vitorflix
