---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aurral-secret-env
  namespace: vitorflix
spec:
  encryptedData:
    SOULSEEK_PASSWORD: AgBxMbJRl2tV7HjGzmUtj1A3835X2Oat/dzwU0vgGTKxsY7Y8ChLZb9sqG5NHDcQMNrFdkbaykAIcjbcJI9Gf/A6RVW0+ATTdYTsXj+Gp3+rrbGtp8+MSU8pVPxMF5Fl3NKZp7pWXVhqZFRPaaTBxs4//b8kcbw34rLl6RTBrf8ylUPuftr0To4M8/pUMREVYawEfueswpQSFvMRqeLuGK2cONi4PuIfvJGLaht/aH7LBes2XDPMEPAQyuFY4CTuiayL+aoIyNEXfi3xYwTkvhjL6q5LP56GD4jUGwbL95rPTSgnnLxgyPWKw9lN//DFKM6oqOlPLyLUYx/GU/9HCm7+qw64zxqvQnJYp1SfemSpK83EJyMY0tFBbia9mth4MCFp2MJzFB0rYeTX/mppP3su3va5ofwg6f6z9HlyyD7IFXRoNUMr/qQ0Hozq/JvfzO49v7gHYYotIMM6XgY1GXnO4yaXsxCtBao4abmvqWgTk/MwelcjvXqeXoE/merTWM+Ju5/GjscatLjuUeATzibf5nfAEWUp6Dr32OVzQgamvwmCj3wm43IZ9BsF54OP46QB3oiCgo9BDBp5uTEJk5tV/Isl+DnBiE/lwNOy4nR+TMTRanZObNxItT3WlO9zb/wnyxYZEAjbaWuo9f974jWf3q0OZBvqJKOhwuSCNgSRpBV/WHUv16uFhm3+WrS2Tb2tEFKYmI2Hsv8NTjEer7o48PHh
    SOULSEEK_USERNAME: AgCVdolK6pqUY7/uY1s9l0M/bgWwSByRGdtQ9kaWb8t027If7UlzoHqbYhHY4byEaRPRZV7S5KbyozewLKbpSTygsDMb8g+n93HZtR3u1vAKLWF+6+ck7Gtdabr34eOhA1qNtvY2pUxscAi0mTjZRG7dNirN1kOmtpp/xqGTDZ7z0HzszeeQoeV/3YCze/ObItdJxn8+aXkcgir6d7D9wkqfvE1LcO7Uj/eR91pb7zOwJ7eQRqokHC7B4/lDdAxyI5O6mmTWRWLgdbuNfZO/X3LjzIkrBb7vn13W1YLkWS+o6iIekQo9Ihro1jxb3WpH+Uq7HzBROp7wRIK0OtrpL9A2jXJBE8J49gCW79Bmal+iOmvi+a/EInIZ8ncnlJsfgIX08vw+eazC4D3I2lvRY8WMn9s8c+8puqfWH1be2/pycuiuZKPnIAvHrO/eBxqULbymfwYHr+HfLHVNqxiLT75zC+ZGunJcgDVvn48+zO3S48ACkATyh4XY//E3D/6yrJ2wLx9DMgn2p4TyeDSANXSL6amIuVIZUTca74POal+4vbg56qBPITQBtDHSHrlKO20psidXnubHL3qhDXYF3xDSYnevlQ3ozx/jaO1XNK8IPAIIKJXJOn61+tbFEi2ncOzsmael+F2g6HoTfF1l5g4O3jkwD9K5cPdVaNoiZgeY/kp+uQb99dqpVakhTTDB/iIcx+N2ILch2+Pj/kiELBsRKA==
  template:
    metadata:
      creationTimestamp: null
      name: aurral-secret-env
      namespace: vitorflix
