---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gluetun-secret-env
  namespace: vitorflix
spec:
  encryptedData:
    HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: AgAiobRQlXDqQERewef6EiPfyYao02JfqoMQwqu3UiK37ReHvcVz2tYpbocaWI3MdNfX0whvSNVhLh+bknHhRWHmBSFPxik2W34qkdbg+jFbiSvM5UJiniMxZH7RsFJ/dpUOugo2nkE4dUzEThp1w/sPvcbM/XeyrJljX+40cwwGXZJNwPfsR54sS7MrPXVFh11sGw2LwJs/Mx42rEUKAGN/FHvRvlDkmKSsdATAwzed+xkPG50aGDyPpqopZAJ8BBNB6xRED1aJlWGylv5GmQRa90SB9x5PDMf2ounVOif0Y3RAOmhBf8AgJXEvQ4RzfLnj99qiOVs60j9pwIt3DGjVym0f0uWwmW1vcYSWsGVGlEqZznNVzibniOzj/E27gTgC2idrD3/QwwuIOm5OHcG+OAZZehHmh9TpL+b8R1uVmBodljfS6KYG4WjSkB4E2HVr73FgPSjsaAK10ytuW72ovSfRqQjPNy3znWLJ2pPOGEykwV343QWSHwTE67fTO9NBI+TL6oNy2QqiPWyMDy9bCs2EA9B1ATjoZ75hKwKRwYycLFrXhY6jJJai4jRSYjcGGsym5rplFEEXWPm5zhmtD2qjp9IwclSTc6/lQsz7OSmzuD5yY6h60h2ltZQOItFab/A3k+/odxQEc61iT5El8e3moJq5Uazovp1VH3PEUyyhJUhosoiZgbm1nMlx8LLYSsblMwb5AoKc2nUisNG27fRdh7qdA6Z8nlsjJxqgcH/fhgOv2ZyZnQWi2CQ=
  template:
    metadata:
      creationTimestamp: null
      name: gluetun-secret-env
      namespace: vitorflix
