---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gluetun-secret-env
  namespace: vitorflix
spec:
  encryptedData:
    HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: AgChwNN7a9uEYmax3pZ3UnY4PdLPZDbvGa7LefOVe39AOdmfFTDaNOhQH9G/4pdrWQ51ij6S5m5XyLU9D8zDpeFblczF6CMruo9dh2+GFkfZ0uHsyaMGgcKsKH+AbpqcJdY7q7zOGixoerTHGSdQpA2QblxetoH0Bzq8MkF1U8x+Kl9PqkDFBRB/o/IAlUCsVPW0b42Zlt6600qW8xbQ4gWJaO7hMmCl+KXg6kVwB8N4EwB0ix2PswVNzn5Lprr882ACdJX7m+oDlj2UsolxTV315yKRPNMqH3+qonBVVyNtQweUV0pGtdhIWzIYwIB/dGFexYTP9Ygr7Mo2un6INmtMEon/OeRGXB3B1vwFXoahxvVXdpC7Fo/dzs3juuDVKfw3e7LFP9pbcgwfiUGxbu7mY5XvTo32wMYrtYaglzldHsW6y1WJWqZYTl56k6WhomeqXgPHZKN6MAH8dTscqwogy2a6udDOEBvjgV3etWauhvst75mN9vyRR6+51sOp0sslqeP//7Yj/oNoVDvLHC0SxyOvibTRs+ut/joL9dCW/LLw6Bhdoyebr4ZZZsM5+pL9j/F3aUZinryx/oaN+zyk0inomk1fp/AXlTnwgYGyZ3cs8je7Hbu9jRzsi/8blzSOlu5UGYsZd+KUnkCp7y3QzD22JDava8ivSh1g04p4nPD4CviLN5A4xGDAfR8VyUSwWSPkqtNct49AtSsmUm/QhiG2u690Nv+2Qj6AgJ0BguMlZfoMP1smi+F8fNQ=
  template:
    metadata:
      creationTimestamp: null
      name: gluetun-secret-env
      namespace: vitorflix
