---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lidarr-downloader-secret-env
  namespace: vitorflix
spec:
  encryptedData:
    LIDARR_API_KEY: AgDEdM61l/d2wzVMEC8EPmSMbTs/RejQc4ycWkX2gd0MScHDqsR31dvXU/w0QcQU1tMSDB4yGvxavPkVUmGMjB0kMk7TnQk3y0pMDPqrEld1SEvPXCaGfVjCl/+mFb859PVjZfJ/FRr1kv6VAhrPOuKJvypruL6AtpKb4e5kKXMcJZobfuMVdedy+7LMbaQDM+tkTl0DhtlUrXrA3yeeOHnshXQVdq+WREbO2ytjDRZv1xg9ieUSoplvTRi6ljSJs+zZa/g096in/nzpAeLnxxJEjMLt+Ho1BtQw9PvscdWyGf8TDnTFhW9wLyNsYG+ZU1vFZpzTD3ZtBnwOouFNfXhtR3iPOhGtAzAOUBEWNIoT8AK3se31Cq3U6o7t0ZLoIb1FX7IcvVlisf6HJ84Ks0mbmndWEoYkXs36iWj/P3T25g25ywPxsU7WkYZNVjam/GZkhk0jjY3DxVEZm5IleHrkQwZzTrJuz/+mBiYZZ9XhpXuSYJ+aKqH0ACI0BpfLuHnlc7xtmCU2zmdpTua+asleU1hekBLfBLTdyhJuflJqb4rmx16tIXy9xBGKlWGCxCmMhWUf5kBbvMFFxjx1wR5xcC4TtGbqUcBQctK3yVtaZMf5azllUJAqndKgsgaqkBjyL3Sitx2ZvUJwFpqYVP9yrKJ7sNJJgRJwGY7GOXuTuPFuz3puPgyJD2nVIlOdZyHzJ1RT/FlrK1pdabouF6X79QiY3jjWaMtRLCPozgccOA==
  template:
    metadata:
      creationTimestamp: null
      name: lidarr-downloader-secret-env
      namespace: vitorflix
