---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: navidrome-secret-env
  namespace: vitorflix
spec:
  encryptedData:
    ND_LASTFM_APIKEY: AgARB38/EH6uglck07ClmPftEyVO8VWfM8WjC+vP+9GfU3Zn5t9QhTANUVfzdUb7prkb8nLMJ7Z8/3BiPUDCQ67y+7CzgR0gMP6fLLf1q00tutgkfHA3cKhNz8ljsdT3s9VSbRYkdTCZ9xsS19GlrglD6DWo0A0DjHrWtWmA8DNI+IbG9sZA/VLl1VbRA9u+8v3sAMpmreFM+dJTs/qvksGOT6a92ukBhzJfCv9EDgwNYufVzF7fnCOdnD0ZjGZKqLFOVVQX/Xp5l9ZWsJNNj+xWZ4PDae3NUotGNp79SZwUMikeiNIXRMWeA7DnP9GegpXEzbdwudTFeBIeYW/LqS5orvIDohdHDFVd49d2BlXw8SovlqHWi5o+e/XNIBuqXMaDTZDg4l3u2vgabsy7NrhnClv6f9L3HlLpZX/hyz9IWarBIVv3UfwhnvtQJXtDpZ7hwDxlFqYD9omHAw5lRJXQ5JM7Fre4ZJSGVGgGEiPtJbmFk13chIgVRnj1zSPUg29KvoKhwXhQnjqIftyCNmYcHsJIbzEPNJ6pcU8dXLNXbVUnPMv57s+nDnenlOHQiqh4VnZd2nyBIVnqPfPONCeW4u4e21eWADJsWLJ3OEtlmwLDK1jQPlWnB8hAExZtilEORtUBn5Owa/TtqYsRqvRbPqIn/WA3qt6XxNKIlE2pKaL5QpeyzVn4LQKZ4JpdcZ2rUVxwBDJ07Px1r1n6R78JSfvra5k8wE4w82+R97qMIA==
    ND_LASTFM_SECRET: AgBCCVUGxioqE0ffRcnWj8k69eKoZmFpNnHumonrm06P52YDfhyzQTKGAL8DdeY/yCBAb3jmwU34MMjXgap16p/dfkB3etUSJIAWkuJ0zF4SvJxcWbCVWmkGJyWPu0tbWwGTpft/q7Ipm22Trht80fnL+f8gm1RMqWcAA1HOy6rPd+LbUNyGTxJapnYgFgqOhUIMjnTwQgF3P3LseujzZ65Py1hAgkLsoGQRTY69NYffGKq49et8Qk1evRDR0ySp2Yx/NC47w0d62pkpxU9/8M5F2Rv4xoTEt462lp88Qhwvusx7hP7H4js5XnVIqqv1fUQmdIc4GXzwXj7aRhsXR6X039M/tPRm6jkwa2auYUsI1mtFF04Pm8TuNwPphpXd0YSZcrtA406SZ6EtVU0VCXi1P1wEtzKp0gPYhRNm6j0pg+s3KnNL/ufLT97amUhtaDrDrNQ/oJccMbGyaVH7aw13Nt994XcSaeUVFL+TUhdBaUMwnjTnG+czADv2IxnzBrI5VExJrxgskYP/p/wcbR79Wsgj1gGiY2YdLLP9Ma8ZYn9LvSzRJqmPBp4qjCFsbaDX3cl8Tc6R3bAz8XcdxscuYqOq1RNiX3gDUkmsfWc+4t3AZFf5x3/fEMvpAN3nErT7TBOg0/CCBG887E4PaHvl4zD7X7AYKPCYp+hSAsBpCG3Ho3QM4lrtlhjcRPKD8NOezZ63Y0lDSwjpRXxTD3NmchDkwtStH3nvlrmdHxRI5Q==
  template:
    metadata:
      creationTimestamp: null
      name: navidrome-secret-env
      namespace: vitorflix
