---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn-auth
  namespace: vitorflix
spec:
  encryptedData:
    openvpn-password: AgAQtxwf5owZAV8etKIZLG887Tq1ehJLhpPRr33g/TzDC+v8BKp8Pvx0pmuM9POH3Cy8+WQl2w/9ElF6jM4vynnB5Q/tcNCcuyPumiW0XjiMDp7kpvt/1tDdPXm0th7qbaGF0FRorwK79AyEtnLmf9Sw+V2HVL4qA0dDteo3MoE7MbpLJqftyBdh52uxL6MNO2NrbDH9T/oMo4JXaDJKNtPwEkZ3+p8dLbOU/NK1GwEAv2gM97M3EuRGcZiOB8Qg024zH7B/iEppEkEUNbzTmPX6WHtMOmvkTrq15FgH5whr7JjoFoEas6E0Z+IBz8j6/pE/hYT6akeIs6OJSmWiv3Uvk7i/s4awL9Xix3ifX1oWCmJ6aHQPjCpJ7sw6WBQJ8VmeZDcVR5gm96qC9Ogq4ytLAKkmNjc77lBTpaq3Kzk6uA1rfPN/uhmQ/3/aOjIiqkCsa/VC+VbpM1H6zmaY03NOvzmf+W7SO/cXhzT3bRKwDOpMqUcqmiJf6IlcjiuR9G7RuF1ZEOfsxRXgeS7ZuvC5p5ydpxnnZWw3jpH7tGX4bLC95+Wp2hcCErFPYi1o377tLNuZEbHwND/ziuK9n83IZP/8p3ICUM+rbQNxcytMRCTJ1d/ZlCvDkuZK6HfzYsNHKXi70THH5a8Dcq19Wv/tw0+vw+0qv0Er4nDzLmaik6r6cUOdjGHPJOk7waFPqC5K0e1iDR2I3rmqwMsn+LB3edeofOBIxLe3XvXIMRx+RQ==
    openvpn-user: AgDJT4BGaBORWhECblfIaBa6wAU96r6nbYg42E6lWGMGDfh2WmvT8gVOmB41AlU7efk/7rFS2oW0OPLCCr0U9J26E0luGpsTnKa+C/9UsUZjgR743tTuftbmgHnf6lfIV8To1W6FdopOXsCshq42jJkYISm+b21Nxj1mp29fbhmIVaipgpBH3raa+oV/sMeKXqjg1lGLgFbr1KZ8uN17AA8w4nsAszdjsrNA3aavXWNWTssswOwDZpxJdq/m6o2mC8xxD/n7lS5/q2Libeel9BQebr8IXgE4YvMkZg25b/8MkD8fhLx26WN8fCsI6zCwpl4F5hZGxxVSdyslodHSBpQFTCk1U50qCt69VCQzncWo0pkvzMJ4k5dYRHpuBgWvnxb3sTMLiSewM4OeZXOUINpG5LQ6Q8jx5y6gabBGejvApKlixjpG+ZbPvHt8PAdXlJg1B0l94WnA8QQ2k76foZf4n7t/aTfyTKoDIDxT4AOpGwgEAiHSV2W/+Srdp+0dvSPd5JWRG1CfrtU8s2lMZO7KAaLB7HPuutUStzwWrW/NxKYNf9qeyxDcafCjHY5YjSFheFH0ccGS/nkUGyPFdHHmAeUyiGRdVjkn/sXjQPAqexFcJyWH2XiMdowwUUBqovqSlIZUuilJ38lw+x/q4AlgtnuVNvumMA6GBivv3KemGOOgXNaNo//K8yxpVuK2NfHp/INHN4aX7xMAnVDgzmENc4FKEg==
  template:
    metadata:
      creationTimestamp: null
      name: openvpn-auth
      namespace: vitorflix
