---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: protonvpn-wireguard
  namespace: vitorflix
spec:
  encryptedData:
    private-key: AgCcXR2kKZfEytPCN6dGw4d4ap5GFz5VfrOYFNI91IMOkCP9tFMlzgturaswMR8MzdwJhJPD9GHVpymFuCwDEMa4MW3pFl1PiwJFkY/B5kwMQR74pgn0K4qEIHGpc45bdcc7O1VTtDiZv6nq/NVoZNIHhJuit0vZU2GwYeb/kUp4jSsHwjJmDmEr3JJIzUsu5mLmHzgyGKxJ2tXIHcWTHEgLgOs3+ylw/lZE1h/JCnf4+FNs8GmVfwStmcOnQ2ZboOVW28vsqcUrGxizHC2aCNKrYiQZI/kN7gMdN4hIl/SbjnxEde7MPLcmme66NFvGbpecPT6/EWskNRcO5m35cRtq16RtCaKGfFoqG4nwpICakNvh39icCiGiL8j3aT0jidHezj9HxXS6SwwdWkxr2WOysbwF8a8UkZ0zL9VMbM+ptbb3HjQc/7X9rvFPoeulqKTtGbwic96dDULZ9jJ/Jo5SwVTBwlm2K5Wuqg8mhIrrUlDYVxJk8TEECDdOCJUYv0KGrdXYJukE87dDb5i1BZY9/K70yvZNrudsIapwFaUz9pApv6TApWYolw82XqatO9EXHxB79utX3iMPINnjYour35X5AbKO3Iem07QggYNO4uRwBbVmCFy9JowoS/ZIfQ4v6rnGbNXAjkzbp1p9pYbO8pskYyFId5lA3jtskxuGWTnISDI7pF12VcZjOuAAARCNFlJBeMxifEf4Ad6VDDh1ftPQUgpJCrGvwVuGjVMNcNKonHQxdIWwu3EFlw==
  template:
    metadata:
      creationTimestamp: null
      name: protonvpn-wireguard
      namespace: vitorflix
    type: Opaque
