---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: protonvpn-wireguard
  namespace: vitorflix
spec:
  encryptedData:
    private-key: AgDG2TPnzXx9NTUTE6bDpE6AJywHkXLLF1VUPev/0R1J+eXT9fgEP9STPVNa9ZAPtClHrCT4dLkicHiMUnIhgFpzWMr7YLuhwEvH1cxBfztzoXX3A7JoWakR6G+Ia7Ku9KU2y0vdhKyP17/ZXlWGAyC8nQm6bBUwzOHsD4F3+0fRHh1P1nBAxXFu4LGXAoTA4ctKTsq+x/JcCtRH7l9zNYRjp7sEsLyR7Elp0Qyu1yHxc8+QIKkGET8ZFCXcrg4il6R7roz7gSnjIQHlK8n2qiM+MkW0SAdiNiXqLTmtqiSWgGs6NDG+iRLchAonkjFZStJ7tewazuVuLzyoYEFwtWQC785m6HYfPk977IeJMtAvSBRy6wW3bcXWCqUGDfHUuXx5rdOVoyC9wuRsgJ/jpmL3ruii6GuAgjF/IPwX1P8RXNTI2Ya8dOhktD/jGZn+II0cZgX28teynLzhphCfEKbOtZBfkHK2zZ209rxgeiE219wRWqHd10D+CULUN/3dtSrbT1ll3ExtdwERTsIlwtPOclufmwdQZPZy2oNj1RHXuR9bSmjdGHM/oosgidBoHSqVp9VBA/cUdUjbnPlfNbcQKh09SKG+UZNW3NT/seGqrg3DRussn9duDV9EUhn89LRsO6dULISnZbI5Mlbz5yvc6ImQ9WHTkWTmJWlc1w0zRjWcT4v4edEyUjHtwVncs5n0Ilr/5tzREd83y4jaKpQTJo60wX+cz2fU75fxjZ1NLlA6nZRa8oD3GjEfUg==
  template:
    metadata:
      creationTimestamp: null
      name: protonvpn-wireguard
      namespace: vitorflix
