---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: soulseek-credentials
  namespace: vitorflix
spec:
  encryptedData:
    SLSKD_SLSK_PASSWORD: AgBBvzl9mykDUJm2ddlCQWQ6XC71+gxVbE6bCfV6xDqlBk5MmOwCWnu2g+uIb+QeokJRXMeBdJnyhjd63xiCZ9q/HWgo3SCQOWhieml36uc12MTTtb8MYD4CtNB2uGqRk+/8sUriRTANtuUCb3Hq5HU9zcjn7JFLEGBLVsAbcwYoKfGGF2QoQWZ5+7sbWuYsZZvPE1rcFZiSYMOAyByNlwH2EuE4cgihi+wkXSwymnuLTxIJ+f/2begyFHSZl6i+g5a6XHA6VZqrlwB2W89+tY+Bq1an9Sl+NJVEcZl4/amCqfnvhG8WL3SSUsDMYtoGlPMB9FdMQI8vT6FFU82eKo/diSfnTFL7Fqtu1AX7Q3rOGgopJXEtJKR4Uvy8Gf7HxDwHnTEB5/TvR/tXF6tuNG6Kilo33LLvaR/Gycj+nRiPnIopKmDWrW636cIYl+GQjE3ve6i+DkZmUFVqhqbi//qx0kInl7aUPceRL3Yay4/jA9sjypDFUtbNNjLs11PmNlAMR2WmwR9vZAZhBIbFi/xdm2nHf/HxUiq2cOVC+1Tbl4US26kJxorOz9uT0LQylziO/PhZfDIRutb6x2KtOKNtqWTkyNQ1MiZZIlO2G4dR71vhRZXsKkRQmLXaVDa5x8yX5fetPomd/rZqbzXwlK5m5/tNKypd+LYcA0FYTXeraJLg26thCFZ36LwBQ4L9IeCsRXW3ziyP2Oazw9imOfczgd10cpo8JtVZyVJtQvbkUfrfcDPHNMso
    SLSKD_SLSK_USERNAME: AgCDrx3AvzeYtXma96efgUsCcnzQF+g7TfBxELTRPEJut4kEn2w+bmx50hDXINQ0gPetc+V8N10ej7M6ZGtFT5/lDy3QzB3fV7sLAW+mwvF3ZyPnUpHyPsFhoVon5urs7QPviN4x+QPnQtufk/8boaHvCzt3ByXe93o5nePG08E3pyFMKa1hIvcZe0QngMgz94234eIAKMUJADzuv9L8YbAzis5EehTE6+EymOlY2aJeGdaPo43c/PaCZiHWY3wOq5pzWK4isWc+Y3xhBrT4qTdmXlpmcOLw8/YmESlrIKv5VbRF0kxqKNWHkHch4Y44g62kcHPF8R9TqNwrE7Eg1rMAJ5FdXXCDAZJgvv1UxNYWe+DyAj69K7Jjv12GKpv1dwpiqIT/JMeKNlj3vedI0KUK4Bg8mB514VD+OzHfG4at2eLuR17YaRWxe5RdK9WCaAKnDYKZewRNA6xzjkSkYphn8GLQOvWV5bTv09X+9/4puzkVp6b/95zCiZ151DpEaDJmeXfJBA9RfmXFly7x6L3nnTfKPoRaFRI6YrcvCBQVcjhFFWerGkRAcRa5GVzg95q/CQ25jGso+Tiu50rKmm9WLXwUTpG1qsIXp5wpFWFBYiPxfaqi69P/IVqCg7h9eyvsFrk6doiJRHJvAZmrfBr1Q0eMGSdYm4WzwzWhs2rzRFJDErHYdwCysCWC1S2eVHbF0NHlO+RTwlAeDQ==
  template:
    metadata:
      creationTimestamp: null
      name: soulseek-credentials
      namespace: vitorflix
