---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vitorflix-api-keys
  namespace: sealed-secrets
spec:
  encryptedData:
    radarr: AgCP5GksCRVtvYdK0ltBPn6JeZfB811F6HuYDv8u8BCrl2eDrUGMOcfFcVidCj7Alh/Vmok0GZGogoXpkl3piTGrhXUFDwE4HWLba6U1jOk7IljpVbCA29rpUEvVL5hEhbwONKrFEDZZ3cyM0fU4AX8/Xy1n+oeGycuthFLFmLh1cz7zzvt1POIbiXpW0zZOifyOHdmdg95fSLnKJm6e9lgTJNiPNSC8ckc7+0J1oAjmb8mIKSq/w6156AiM4ZxlNzmM0HRrkvRi/ty9SncR8XyQwo4H4CrbW75tvdyDXkDBAa3OkeMgxoeJ4ggz9lPS8ta0BhNpgQwbmH/hSaRykrmFkS5VIMXv1hl4B3In1htZVE1npT/yuXEUsp9inX61kGl+xS8S2KVqT1LUfuOHMpfViIa3NZqY3B3RTXsstuxM5uMC5gqHswwnYcFSwR4zubzpoai5Wt6DpyxWmDE07kx53hdNXiSuMC+nJp9dTG/JYhULLRol8Qf/bGTIV/JuyjxeH3R4+Ihyme+kTnxIFIf9txTxw8XhbjlnaiLRI6U6bX7VLZwGOasVcJpFzwF8EcY5C+YY+BhtWPqU3iqfNxyRvR50wVY4lnTLDCTzp4S+Yp+AGBWX70Z7Ocl8rreikejEFAMbDXWYnZDlaTvu/FwevWy5PqWgqMg6E2XoRu+mRAFWGmIwl4LDP5v7AAOsmmL10Cs7TINgtIiiQpa8WV1s098jkTjQ3CEE1mcBQfapTg==
    sonarr: AgBUvs1k1jn+0aZDErFvy6qn3B8oDJDca7CIzfaEWMnxsuHxYj0JtoKuchieIuspvvaKbQ+bUbckOzKVtd08Y3QqIpSAxqVuEw3kB1OstxQLWRXijDImmTxZ+w7tjVfr6PLngbma1aoKJ5jr1Hn3HJvF9b4tBukhEMhtloremK4mmWqrkCyVI3VnL8JR5hchzDSogJ1Mi4aeTgUlcDx/kxNII7MsXkJCWMIMCLTNe2Z5zUymzTSgCe4hhuembWtgysDprLaQm7GJERfttk+hUAe0062U3yERrzV6M1GSN9zkFfWtoo2wXpmA+G33cPjaG9fl5HXjmVpfTQlCYwnnX7pZ0r6OLSnMH3085/+qft/HuWnIlPM5XiliqfTMbngId8altuXPHCiEbF31YGNmP9f371mEPj0/4tv9+s4Z9/5u1jbpctcbiOSOErjIl3TS4S06ScCrz5E8KpM1WmWHaJbTh7bYyZtVWhF6zvmMYXeQlVT5aFv7yi40+rgedk5uKeKRNFdMNT6NPt/exggmHpxafIn+AWiC0As1SqxqDv86UZ3m7IUzLbO9Z4F19aYXOIUqVS02PBL02uCXhFuJwszlp2jIjriTH/NKdi02Zwqr5GCPmtTRhYGfgehNit1o1zFzXF/0nApGUM5yjmUYv4T7posJedd/yvacQ0i2xflirN94z6Eu5y/LMPDjL+So6p+YmbdZ0++Lu2dCqQ5QMsPbmm9CgiZE6fUmLIhGMnd7gw==
  template:
    metadata:
      creationTimestamp: null
      name: vitorflix-api-keys
      namespace: sealed-secrets
