---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vitorflix-api-keys
  namespace: vitorflix
spec:
  encryptedData:
    radarr: AgCq48eaQtIbXpqY/IKFrt86njog+JdPppZ1L5zdESOzyQM6GiVx8Wko7ynP/+EfKyeiV81dB+/traDWRwDgKm5aMxno/7zGAlOAasj0k4kA3NavgBDDz4eGh/z2ixdWyOOamEKTZnv3eVyZZ+CRF9FadXx2mmLrts+8fmiB0y2qr/JYRCxUcapZ4/9RqepEf2wDZZDAmmRo/JOoj2tEBeI4cqbey+XXpLtnMGwDont26xdPPc4uJzQmSZO7mENHord6odC1vhaI60kEp5L5KNliELd1La/GABhYJeK0JuDmPuq7XwdyUFG8pWGW+vHGqkC3qFJk1x4gubAa7wLTC/lD37u8ZZa6cmQ2nbQcQE5fSiiZWEr+7MVBIpWXdI5OXllGEWG0vZbd9IU+VHGNBRVY3QvUka63B1qErGWFMNyRcDMePf0wbEseAc5nodPV8PiywIMcuIboATN6mrhnrmJdNwqgTv+G4uoPkql763IffMgjO826OO9y7KsjmxbFbR436K4Apgvn5jf14Si5C+xMczUDAKAy5CeObKFTHMyHPc+civ0RjNn2ddo7Fxe6FMGtzmISa3+K6aVa/JhoNuci2C0VsRFa361FtYlJM2sYGNZy4FwMx3LmBQRymIuLq3gIDEzzlhcFEs9PrbLwgD5L449KUoO9z0qe846sHPa/T32ej2BDK0Uz2xC9+ttF1gNBqYi6kGJPbUFgq88W0MAie5o9a3wm9McuXlIaOqErPA==
    sonarr: AgAcf51bCMHTuwWKOphaS1RnNgcC+trtmtJve8N/KfDW1b2MazdKLh/PlWrzPyY1jYDUEeeIePcjHdtR3p/vhNuIorGvWewMCteLZB61DpoFmI3XJ7WMzJ/Gj4FsWvQpbWXxC1yk42KmSe//U72t+7DrtXaup7+N2oWDUZG8B5hmiL0lqoWgyHjYlpHJWdznpprOrVonyxEB2OAf7+HS5WOukraX+tR6bfeHmCUwSNYXaBN9uT7fMs8uNR0a1JpjrhdMTKuTHEE5M+t1JODszf9HJ+3+aUNgYN4PgYcDQz7joUBZvWZFrfac0NpfeTYou/Qak7o6GLpY1oAh+lZeUX6tLodSLOVYT282fBVvlmafMf9IradfRS/dJ8wl0rfzq9uOg9ITpH8NPAOxij7CMPeFCrRhE0CwMalZqaIHKSzhSjIE/LUFJBpnm0Xm4YKPe9BeXFWM4tk2n3NAj4H1lhjnW3N9J1WRlLK3jo9ak05j8PAElfd1R0AlYToML9JEF9PGgLwUrzJYOJXqotWizfQALAUBPvwX8FDsUvz0HxXVTyKRgoI4kKP9x5ALzWHEBztbMf1AHWjr27qzOQCfpIwDVUwY51ES8SMFoxw/mNEdoEvhJkSxUThh4sl4BkiMm+/Js/eavzJXcho1Qf8Xi7KKqdmFc9JNvhPIIN6Inf0nbjI32ZVVuO/ys9O0TvJu64pHpoScl2FRVLra1bkEctKlZgafHcm3rjico+UCtQppdw==
  template:
    metadata:
      creationTimestamp: null
      name: vitorflix-api-keys
      namespace: vitorflix
