apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bazarr
  name: bazarr
spec:
  ports:
  - port: 6767
    protocol: TCP
    targetPort: 6767
  selector:
    app: bazarr