apiVersion: v1
kind: Service
metadata:
  namespace: vitorflix
  labels:
    app: jellyseerr
  name: jellyseerr
spec:
  ports:
  - name: 5055-5055
    port: 5055
    protocol: TCP
    targetPort: 5055 
  selector:
    app: jellyseerr
  type: ClusterIP
