apiVersion: v1
kind: Service
metadata:
  namespace: vitorflix
  labels:
    app: jellyfin
  name: jellyfin
spec:
  ports:
  - name: 8096-8096
    nodePort: 30067
    port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app: jellyfin
  type: NodePort
