apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prowlarr
  name: prowlarr
  namespace: vitorflix
spec:
  ports:
  - port: 9696
    protocol: TCP
    targetPort: 9696
  selector:
    app: prowlarr
