apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prowlarr
  name: prowlarr
spec:
  ports:
  - port: 9696
    protocol: TCP
    targetPort: 9696
  selector:
    app: prowlarr
status:
  loadBalancer: {}
