apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-23T23:52:03Z"
  labels:
    app: qbittorrent
  name: qbittorrent
  namespace: vitorflix
  resourceVersion: "555958"
  uid: 7359b7d5-03d3-4d7e-a79f-092cfacc35b7
spec:
  clusterIP: 10.101.218.149
  clusterIPs:
  - 10.101.218.149
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: qbittorrent
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
