apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: radarr
  name: radarr
spec:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app: radarr
status:
  loadBalancer: {}
