# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    com.docker.official-images.bashbrew.arch/media-servicesjelly-qbit-toggle1: amd64
    io.kubernetes.cri-o.ContainerType/gluetun-container: container
    io.kubernetes.cri-o.ContainerType/gluetun-qbittorrent-port-manager: container
    io.kubernetes.cri-o.ContainerType/media-servicesjelly-qbit-toggle1: container
    io.kubernetes.cri-o.ContainerType/qbittorrent: container
    io.kubernetes.cri-o.SandboxID/gluetun-container: 2a7b12f1c98d365cbf3915e94dc427bd04eed0a3a8f0b1a0c4b3225d8769065
    io.kubernetes.cri-o.SandboxID/gluetun-qbittorrent-port-manager: 2a7b12f1c98d365cbf3915e94dc427bd04eed0a3a8f0b1a0c4b3225d8769065
    io.kubernetes.cri-o.SandboxID/media-servicesjelly-qbit-toggle1: 2a7b12f1c98d365cbf3915e94dc427bd04eed0a3a8f0b1a0c4b3225d8769065
    io.kubernetes.cri-o.SandboxID/qbittorrent: 2a7b12f1c98d365cbf3915e94dc427bd04eed0a3a8f0b1a0c4b3225d8769065
    io.kubernetes.cri-o.TTY/gluetun-container: "false"
    io.kubernetes.cri-o.TTY/gluetun-qbittorrent-port-manager: "false"
    io.kubernetes.cri-o.TTY/media-servicesjelly-qbit-toggle1: "false"
    io.kubernetes.cri-o.TTY/qbittorrent: "false"
    io.podman.annotations.autoremove/gluetun-container: "FALSE"
    io.podman.annotations.autoremove/gluetun-qbittorrent-port-manager: "FALSE"
    io.podman.annotations.autoremove/media-servicesjelly-qbit-toggle1: "FALSE"
    io.podman.annotations.autoremove/qbittorrent: "FALSE"
    io.podman.annotations.init/gluetun-container: "FALSE"
    io.podman.annotations.init/gluetun-qbittorrent-port-manager: "FALSE"
    io.podman.annotations.init/media-servicesjelly-qbit-toggle1: "FALSE"
    io.podman.annotations.init/qbittorrent: "FALSE"
    io.podman.annotations.privileged/gluetun-container: "TRUE"
    io.podman.annotations.privileged/gluetun-qbittorrent-port-manager: "FALSE"
    io.podman.annotations.privileged/media-servicesjelly-qbit-toggle1: "FALSE"
    io.podman.annotations.privileged/qbittorrent: "FALSE"
    io.podman.annotations.publish-all/gluetun-container: "FALSE"
    io.podman.annotations.publish-all/gluetun-qbittorrent-port-manager: "FALSE"
    io.podman.annotations.publish-all/media-servicesjelly-qbit-toggle1: "FALSE"
    io.podman.annotations.publish-all/qbittorrent: "FALSE"
    org.opencontainers.image.base.digest/gluetun-qbittorrent-port-manager: sha256:bb89f137c6111ede52c3974d59f60ac2a8e2df4580e4905958031240
    org.opencontainers.image.base.digest/media-servicesjelly-qbit-toggle1: sha256:6d4ad45d5ee9229245c81694752a142576823d7163afd7267d249c95
    org.opencontainers.image.base.name/gluetun-qbittorrent-port-manager: docker.io/library/alpine:latest
    org.opencontainers.image.base.name/media-servicesjelly-qbit-toggle1: docker.io/library/python:3
    org.opencontainers.image.created/media-servicesjelly-qbit-toggle1: "2024-08-07T15:49:22Z"
    org.opencontainers.image.revision/media-servicesjelly-qbit-toggle1: cc2cf19f2c9a440706d17b5937bf104052eef967
    org.opencontainers.image.source/media-servicesjelly-qbit-toggle1: https://github.com/docker-library/python.git#cc2cf19f2c9a440706
    org.opencontainers.image.url/media-servicesjelly-qbit-toggle1: https://hub.docker.com/_/python
    org.opencontainers.image.version/media-servicesjelly-qbit-toggle1: 3.12.5-bookworm
  creationTimestamp: "2024-08-17T00:52:06Z"
  labels:
    app: gluetun
  name: gluetun
spec:
  automountServiceAccountToken: false
  containers:
  - image: localhost/jelly-qbit-toggle:latest
    restartPolicy: Always
    name: media-servicesjelly-qbit-toggle1
    ports:
    - containerPort: 5000
      hostPort: 5000
    - containerPort: 6881
      hostPort: 6881
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 8388
      hostPort: 8388
    - containerPort: 8888
      hostPort: 8888
    - containerPort: 6881
      hostPort: 6881
      protocol: UDP
    - containerPort: 8388
      hostPort: 8388
      protocol: UDP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  - env:
  #  - name: FIREWALL_DEBUG
  #    value: "on"
    - name: SERVER_COUNTRIES
      value: canada
    - name: VPN_SERVICE_PROVIDER
      value: protonvpn
    - name: PORT_FORWARD_ONLY
      value: "on"
    - name: VPN_PORT_FORWARDING
      value: "on"
    image: docker.io/qmcgaw/gluetun:latest
    name: gluetun-container
    restartPolicy: Always
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /gluetun
      name: docker-appdata-gluetun-host-0
    - mountPath: /tmp/gluetun
      name: docker-appdata-gluetun_tmp-host-1
  - env:
    - name: DOCKER_MODS
      value: "ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest"
    - name: WEBUI_PORT
      value: "8080"
    - name: PUID
      value: "1"
    - name: PGID
      value: "1"
    image: lscr.io/linuxserver/qbittorrent:5.0.3 ## using this version for qbit_manage compatibility
    name: qbittorrent
    restartPolicy: Always
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /config
      name: docker-appdata-qbittorrent-host-0
    - mountPath: /data
      name: data-host-1
  - image: patrickaclark/gluetun-qbittorrent-port-manager:latest
    name: gluetun-qbittorrent-port-manager
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /tmp/gluetun
      name: docker-appdata-gluetun_tmp-host-0
    - mountPath: /qbit-healthcheck.sh
      name: home-podman-docker-projects-media-services-qbit-healthcheck.sh-host-1
  - env:
    - name: QBT_TAG_UPDATE
      value: "false"
    - name: QBT_REM_ORPHANED
      value: "true"
    - name: QBT_REM_UNREGISTERED
      value: "false"
    - name: QBT_DIVIDER
      value: =
    - name: QBT_LOGFILE
      value: activity.log
    - name: QBT_CONFIG
      value: config.yml
    - name: QBT_WIDTH
      value: "100"
    - name: QBT_TAG_TRACKER_ERROR
      value: "false"
    - name: QBT_SKIP_CLEANUP
      value: "false"
    - name: QBT_CAT_UPDATE
      value: "true"
    - name: QBT_LOG_LEVEL
      value: INFO
    - name: QBT_DRY_RUN
      value: "false"
    - name: QBT_CROSS_SEED
      value: "false"
    - name: QBT_RECHECK
      value: "false"
    - name: QBT_RUN
      value: "false"
    - name: QBT_TAG_NOHARDLINKS
      value: "true"
    - name: QBT_SCHEDULE
      value: "30"
    image: docker.io/bobokun/qbit_manage:latest
    name: qbitmanage
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /config
      name: docker-appdata-qbit_manage-host-0
    - mountPath: /data
      name: data-host-1
  enableServiceLinks: false
  hostname: gluetun
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /docker/appdata/gluetun_tmp
      type: Directory
    name: docker-appdata-gluetun_tmp-host-0
  - hostPath:
      path: /home/podman/docker-projects/media-services/qbit-healthcheck.sh
      type: Directory
    name: home-podman-docker-projects-media-services-qbit-healthcheck.sh-host-1
  - hostPath:
      path: /docker/appdata/gluetun
      type: Directory
    name: docker-appdata-gluetun-host-0
  - hostPath:
      path: /docker/appdata/gluetun_tmp
      type: Directory
    name: docker-appdata-gluetun_tmp-host-1
  - hostPath:
      path: /docker/appdata/qbittorrent
      type: Directory
    name: docker-appdata-qbittorrent-host-0
  - hostPath:
      path: /docker/appdata/qbit_manage
      type: Directory
    name: docker-appdata-qbit_manage-host-0
  - hostPath:
      path: /data
      type: Directory
    name: data-host-1
status: {}
