# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate : "registry"
    io.kubernetes.cri-o.TTY/radarr: "false"
    io.podman.annotations.autoremove/radarr: "FALSE"
    io.podman.annotations.init/radarr: "FALSE"
    io.podman.annotations.privileged/radarr: "FALSE"
    io.podman.annotations.publish-all/radarr: "FALSE"
  creationTimestamp: "2024-12-24T19:19:15Z"
  namespace: vitorflix
  labels:
    app: radarr
  name: radarr
spec:
  restartPolicy: Always
  automountServiceAccountToken: false
  containers:
  - env:
    - name: PGID
      value: "1"
    - name: PUID
      value: "1"
    image: ghcr.io/hotio/radarr:latest
    name: radarr
    ports:
    - containerPort: 7878
      hostPort: 7878
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /config
      name: docker-appdata-radarr-host-1
    - mountPath: /data
      name: data-host-2
  enableServiceLinks: false
  volumes:
  - hostPath:
      path: /docker/appdata/radarr
      type: Directory
    name: docker-appdata-radarr-host-1
  - hostPath:
      path: /data
      type: Directory
    name: data-host-2
