apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Node Feature Discovery
  - https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.17.2
  # NFD rules for Intel HW
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=v0.32.0

configMapGenerator:
  - name: nfd-worker-conf
    behavior: replace
    files:
      - nfd-worker.conf

patchesStrategicMerge:
  - namespace-patch.yaml 