# jellyfin/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: vitorflix
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
spec:
  ingressClassName: traefik # It was cilium before
  # tls:
  #   - hosts:
  #       - jellyfin.vitorflix.club
  #     secretName: jellyfin-ingress-tls
  rules:
    - host: jellyfin.vitorflix.club
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096

