apiVersion: v1
kind: ConfigMap
metadata:
  name: slskd-configmap
  namespace: vitorflix
data: 
  slskd.yml: |
    integrations:
      vpn:
        enabled: true
        port_forwarding: true
        polling_interval: 2500
        gluetun:
          url: http://localhost:8000
          timeout: 1000
    directories:
      incomplete: '/data/slskd/incomplete'
      downloads: '/data/slskd'
    transfers:
      upload:
        speed_limit: 610 # in kibibytes (equals 5Mb)
    remote_file_management: true
    shares:
      directories:
        - '/data/media/music'
        - '/data/media/movies'
        - '/data/media/tv'