apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi-plugin
  namespace: argocd
spec:
  destination:
    namespace: csi-proxmox
    server: https://kubernetes.default.svc
  source:
    path: argocd/proxmox-csi-plugin
    repoURL: https://github.com/RelicCornhusk/homelab.git
    targetRevision: HEAD
  sources: []
  project: default
