apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: ynab-autosplit
  name: ynab-autosplit
spec:
  concurrencyPolicy: Forbid
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ynab-autosplit
        spec:
          restartPolicy: OnFailure
          containers:
          - name: ynab-autosplit-vitor
            image: ghcr.io/reliccornhusk/ynab-autosplit:1.1.0
            envFrom:
            - secretRef:
                name: ynab-autosplit-env-vitor
          - name: ynab-autosplit-thais
            image: ghcr.io/reliccornhusk/ynab-autosplit:1.1.0
            envFrom:
            - secretRef:
                name: ynab-autosplit-env-thais

