apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  destination:
    namespace: gateway
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/RelicCornhusk/homelab.git 
    targetRevision: HEAD
    path: argocd/gateway
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true