apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins
  namespace: argocd
spec:
  destination:
    namespace: intel-device-plugins
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://intel.github.io/helm-charts
      targetRevision: 0.32.0
      chart: intel-device-plugins-operator
      helm:
        values: |
          name: igpu
          sharedDevNum: 0
          nodeFeatureRule: false
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: 'true'
        parameters:
        - name: installCRDs
          value: "true"
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true