apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins
  namespace: argocd
spec:
  destination:
    namespace: intel-device-plugins
    server: https://kubernetes.default.svc
  source:
    path: argocd/intel-device-plugins
    repoURL: https://github.com/RelicCornhusk/homelab.git
    targetRevision: HEAD
    kustomize: {}
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
