apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins
  namespace: argocd
spec:
  destination:
    namespace: intel-device-plugins
    server: https://kubernetes.default.svc
  source:
    path: argocd/intel-device-plugins/gpu
    kustomize:
      namePrefix: intel-device-plugins-gpu-
      helmGlobals:
        enableHelm: true  # Enable Helm support
    repoURL: https://github.com/RelicCornhusk/homelab.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
