apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 87.15.2
      chart: kube-prometheus-stack
      helm:
        values: |
          # Disable scraping for components that don't expose default metrics in your K8s distro
          kubeControllerManager:
            enabled: false
          kubeScheduler:
            enabled: false
          kubeProxy:
            enabled: false

          grafana:
            persistence:
              enabled: true
              type: pvc
              size: 5Gi
            
          prometheus:
            prometheusSpec:
              retention: 7d
              retentionSize: "0"
              resources:
                requests:
                  memory: 384Mi
                  cpu: 100m
                limits:
                  memory: 640Mi
                  cpu: 500m
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 20Gi

          alertmanager:
            tplConfig: false
            alertmanagerSpec:
              configSecret: "custom-alertmanager-config"
    - repoURL: https://github.com/RelicCornhusk/homelab.git
      targetRevistion: HEAD
      path: argocd/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged