apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.1
    chart: sealed-secrets
    helm:
      parameters:
        - name: fullnameOverride
          value: sealed-secrets-controller
        - name: namespace
          value: kube-system
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
