apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vitorflix
spec:
  destination:
    namespace: vitorflix
    server: https://kubernetes.default.svc
  source:
    path: argocd/vitorflix
    repoURL: https://github.com/RelicCornhusk/homelab.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true