apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins
  namespace: argocd
spec:
  destination:
    namespace: intel-device-plugins
    server: https://kubernetes.default.svc
  source:
    - repoURL: https://intel.github.io/helm-charts
      targetRevision: 0.32.0
      chart: intel-device-plugins-gpu
      helm:
        parameters:
        - name: includeCRDs
          value: "true"
        values: |
          nodeFeatureRule: false
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true